### ISSUE TITLE
[Style] 추가 익스텐션 구성

### ISSUE THREAD

**Issue by hooni0918** [SOPT-all/35-COLLABORATION--iOS--SaftyReport#14]
## 작업할 브랜치
- `style#14- Makeextension` 브랜치에서 작업합니다.

## ✔️ To-Do
- [ ] 폰트 익스텐션을 만듭니다
- [ ] 컬러 익스텐션을 만듭니다
- [ ] addSubview 익스텐션을 만듭니다
