### ISSUE TITLE
Style: MainViewUI짜기 시작

### ISSUE THREAD

**Issue by HEHEEUN** [SOPT-all/35-COLLABORATION--iOS--SaftyReport#31]
## 📝 작업 페이지 캡쳐
|    페이지    |   캡쳐   |
| :-------------: | :----------: |
| 피그마 | <img src = "https://github.com/user-attachments/assets/54e00847-cec8-4d7a-97ab-97c8deaeabc0" width ="250"> 

## 작업할 브랜치
- `style/#31-MainViewUI` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] MainViewUI - CompositionalLayout 기반 작업
  - [x] CollectionView - Compositional Layout을 통해 Main Page구현 
  - [x] group별로 들어갈 cell작업
  - [x] MyReport Cell (=item2개) 작업하기
  - [x] 배너 임시 이미지 넣기 -> scroll 작업 에정
  - [x] 주요 처리 사례 스택뷰로 처리해서 넣기
 - [x]  BannerScroll작업 넣기 *** → 이게 되면 자동으로 주요 처리 사례 scroll작업도 편하게 넣을 수 있을듯
- [x]  나의 올해 신고 건수 컬러링 처리
- [x]  subReportCountLabel 컬러링 처리
- [x]  나의 올해 신고 cell에 image 넣기
- [x]  이번달 신고 image 넣기
